### ISSUE TITLE
Pid Tuning w/ LUA script takes too line because of decimals

### ISSUE THREAD

**Issue by jrgutier** [fedorcomander/kissfc-tx-lua-scripts#12]
Having floating numbers is awesome.  However, it actually takes a long time to get to +1 of what you had previously (100 clicks).

Is there a way to have the interval change from .01 to something bigger as you hold down a button? Kind of how it works on an oven timer.

**Comment by BigBangPro** [comment]
Code is already using the 'hold down button' event==EVT_PLUS_FIRST or event==EVT_PLUS_REPT 
It can increase a whole integer pretty quick even using 0.1 increments 

I gues you could split the two events and have a larger step for EVT_PLUS_REPT

**Comment by fedorcomander** [comment]
Added fast number changes when holding the button + and -
