### ISSUE TITLE
Crash on Taranis QX7 2.2.0 Final

### ISSUE THREAD

**Issue by Chefhandwerker** [fedorcomander/kissfc-tx-lua-scripts#17]
Hello, since the update to the 2.2.0 Final of the QX7. The script crashes when you change the PID's or the Rates settings. The filters and VTX adjustment works perfectly

**Comment by fedorcomander** [comment]
video please. i test on X9... Alex WOlf - on his X7. Seems both of us are happy.

**Comment by fedorcomander** [comment]
(i do use RC18, still need to upgrade to 2.2 final)

**Comment by Chefhandwerker** [comment]
I think the problem is solved,
It was opentx. I reflashed 2.2.0 Final, and now it seems to run.

**Comment by awolf78** [comment]
I am also still on RC18 BTW
