### ISSUE TITLE
Filters tab script syntax error

### ISSUE THREAD

**Issue by mustang967** [fedorcomander/kissfc-tx-lua-scripts#24]
I'm getting this issue everytime I get to the filters tab. 
![fullsizerender 2](https://user-images.githubusercontent.com/9469321/29738870-5fcb933a-89e4-11e7-9b6f-f7ebca7db508.jpg)
I tried looking through the code but I don't really know anything about lua. 
I'm running the latest lua script with kiss FC 1.3RC25

**Comment by fedorcomander** [comment]
try change pages slower.;)

**Comment by BigBangPro** [comment]
Do you think a handle for enter break too fast could be a getTime + 50ish to allow the page to complete loading?

**Comment by BigBangPro** [comment]
**correction menu break

**Comment by fedorcomander** [comment]
I think it happens when you send request, then change page, and response arrives. but i really have no time to look into that atm.

**Comment by mustang967** [comment]
So how slow are we talking here? Regardless of the amount of time I wait I still get the same error. I've found that I can quickly jump past the filters page and get to the next page(Alarms) but as soon as I stop on the filters page it throws that script error and I have to restart my taranis to be able to use the other pages. Any changes I can try?

**Comment by BigBangPro** [comment]
Are you sure you have the right lua version of the kiss folder. The code of the filters page changed  in v0.8 to accommodate the notch filtering.
Check carefully when copying the 'kiss' folder to your sd card

**Comment by mustang967** [comment]
I just downloaded it again directly from the release with the exact issue. I've tried placing the x7 and the horus version of the filters lua file but no luck. Any ideas for ways to troubleshoot this issue? I've just checked with opentx and I'm running the most recent version 2.2.0. Any chance I could get someone's filters luac file to test? Could it be an internal compiling error?

**Comment by fedorcomander** [comment]
Btw, do u use latest firmware on kiss???? Filters have extra fields there!!!

**Comment by mustang967** [comment]
I am using the lastest RC. Not having the Filters tab available isn't the end of the world but it would be nice to have. I'm guessing no one else is having any issues.

**Comment by gotnull** [comment]
I get this issue 90% of the time as well and I'm forced to have to restart the Taranis (X9D+). Latest KISS FC FW and LUA Scripts.

**Comment by mustang967** [comment]
I reflashed my FC directly from the kiss configurator and It fixed the issue. I'm not sure what exactly happened but its working now.
