### ISSUE TITLE
FIRMWARE v1.3RC30 Problem with lua script 

### ISSUE THREAD

**Issue by germanwt** [fedorcomander/kissfc-tx-lua-scripts#26]
Hello 
I have the XSR receptor and a tbs unify hv pro, and doesnt work the lua script in my taranis 
I had the firmware v1.2 and showed values in my taranis ok but the firmware v1.3 doesnt work and i cant see nothing. 
I copy the lua script "KissCF.lua" and script file, and I choose and screen 1 Select "Script" but doesnt work 
Do you have any idea for resolve this problem ?? 

Thanks

**Comment by fedorcomander** [comment]
what fw do u use? try with latest 1.3RC30

**Comment by germanwt** [comment]
I tried with latest 1.3RC30 the Lua script but doesnt work in the taranis.
Dont show me nothing in the display. "Error"

**Comment by lovincup** [comment]
@germanwt  - "KissCF.lua" is for crossfire. You need KissSP.lua which is for smartport on you XSR.

**Comment by germanwt** [comment]
I tried with KissSP.lua for smartport in my XSR and dont show me nothing in the display. "Error"

**Comment by lovincup** [comment]
On your Taranis screen setup, is the script option looking for the proper script? On previous versions, the lua scripts were named differently.

I would delete the files on the SD card, re-copy them to the Taranis and triple check the Taranis screen setting.

Maybe reflow your connections to the FC.

That's all I got.

**Comment by germanwt** [comment]
I already solved the problem you have to copy to the script folder the kissSP.lua and the other folder of kiss

Many thanks to all for the collaboration
