### ISSUE TITLE
Script panic

### ISSUE THREAD

**Issue by jrgutier** [fedorcomander/kissfc-tx-lua-scripts#4]
Getting 

Script panic
not enough memory

When I try to launch the script

**Comment by fedorcomander** [comment]
otx version?
other scripts running?

---
Cheers,
Alex

**Comment by jrgutier** [comment]
X9D+ Special Edition
Latest Version OpenTX 2.2 N365

https://github.com/betaflight/betaflight-tx-lua-scripts is running and works.

**Comment by jrgutier** [comment]
Found the problem. Was running both the BetaFlight lua and KISS lua on same model. Having an exclusive model fixes it.

**Comment by fedorcomander** [comment]
That explains a lot. Glad u sort it out.
