### ISSUE TITLE
Some refactoring

### ISSUE THREAD

**Issue by fedorcomander** [fedorcomander/kissfc-tx-lua-scripts#7]
Hi guys!

I think i shoot 2 rabbits with one shot. Take a look on https://github.com/fedorcomander/kissfc-tx-lua-scripts/tree/common_scripts branch... Sources are separated and makefile build final lua scripts, consumable by end user. I still have to refactor horus stuff, but X7 and taranis should be working (but not yet tested by me).. What do u think?

use make to build scripts.

**Comment by BigBangPro** [comment]
love the idea - standardise where possible.  great work

**Comment by fedorcomander** [comment]
Added luac compilation ;)))

**Comment by awolf78** [comment]
Great idea!
Installing cygwin ;)

**Comment by awolf78** [comment]
X7 version has a syntax error in line 551 "attempt to get length of..." (rest is cut off due to small screen in X7).
Tried to debug in simulator, but it won't let me open menu without telemetry. Will try again later when I have a bit more time.

**Comment by awolf78** [comment]
menuList and menuActive needs to be global - then it works ;)

**Comment by fedorcomander** [comment]
Ok, my new script works like a champ on Taranis...

**Comment by fedorcomander** [comment]
Guys, i've merged common branch. So - knock yourself on master now :)
